export enum AppState {
    FETCHING_AUTH_DATA,
    FETCHING_NONE,
    LOGIN_USER_AS_ADMIN,
    LOGIN_USER_AS_GUEST,
    LOGIN_USER_AS_MERCHANT,
    LOGIN_USER_AS_MASTER,
    POPUP_LOGIN_MODAL,
    POPUP_REGISTER_MODAL,
    POPUP_NO_MODAL,
    POPUP_FORGET_MODAL,
    Send_Mail_TO_USER



}




